apiVersion: apps/v1
kind: Deployment
metadata:
  name: place-service
  namespace: moamap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: place-service
  template:
    metadata:
      labels:
        app: place-service
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ncr-cred
      containers:
        - name: place-service
          image: REPLACE_ME_NCR/moamap/place-service:latest
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: moamap-config
            - secretRef:
                name: moamap-secrets
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
      volumes:
        - name: tmp
          emptyDir: {}
